<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8CAR6C7" failures="1" tests="1" name="runners.FuturePayBillRunner" time="25.105" errors="0" timestamp="2025-03-17T22:35:36 IST" skipped="0">
  <testcase classname="runners.FuturePayBillRunner" name="runScenario" time="25.105">
    <failure message="expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinitions.FuturePayBillSteps.user_should_see_success_message(FuturePayBillSteps.java:78)
at âœ½.User should see a confirmation message "The bill payment has been scheduled successfully."(file:///C:/Users/dpraj/Downloads/Zero_Bank/Zero_Bank/Zero_Capston_Project/src/test/resources/features/FuturePayBill.feature:15)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.FuturePayBillRunner -->
