<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8CAR6C7" failures="3" tests="16" name="runners.TestRunner" time="263.618" errors="0" timestamp="2025-03-19T09:45:58 IST" skipped="0">
  <testcase classname="runners.TestRunner" name="runScenario" time="11.639"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="18.157"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="19.089"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="17.773">
    <failure message="Error message mismatch! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at stepDefinitions.ExcessFundSteps.user_should_see_the_error_message_excess(ExcessFundSteps.java:84)
at ✽.User should see the error message "Insufficient funds" for excess fund transfer(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/ExcessFund.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="14.615"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="21.766"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="18.480"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="19.423">
    <failure message="expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinitions.FuturePayBillSteps.user_should_see_success_message(FuturePayBillSteps.java:81)
at ✽.User should see a confirmation message "The bill payment has been scheduled successfully."(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/FuturePayBill.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="18.810"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="17.709"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="19.609"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="18.151"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="5.366"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="21.249"/>
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="17.262">
    <failure message="Error message mismatch! expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message mismatch! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at stepDefinitions.NegativeAmountSteps.user_should_see_the_error_message_negative_amount(NegativeAmountSteps.java:81)
at ✽.User should see the error message "Invalid amount entered" for negative amount transfer(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/NegativeAmount.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.TestRunner" name="runScenario" time="4.520"/>
  <system-out/>
</testsuite> <!-- runners.TestRunner -->
