<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8CAR6C7" failures="3" tests="16" name="ZeroBank Tests" time="264.888" errors="0" timestamp="2025-03-19T09:45:58 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.766"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.709"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="21.249"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.52"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.773">
    <failure type="java.lang.AssertionError" message="Error message mismatch! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message mismatch! expected [true] but found [false]
at stepDefinitions.ExcessFundSteps.user_should_see_the_error_message_excess(ExcessFundSteps.java:84)
at ✽.User should see the error message "Insufficient funds" for excess fund transfer(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/ExcessFund.feature:12)
... Removed 3 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.423">
    <failure type="java.lang.AssertionError" message="expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]">
      <![CDATA[java.lang.AssertionError: expected [The payment was successfully submitted.] but found [The bill payment has been scheduled successfully.]
at stepDefinitions.FuturePayBillSteps.user_should_see_success_message(FuturePayBillSteps.java:81)
at ✽.User should see a confirmation message "The bill payment has been scheduled successfully."(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/FuturePayBill.feature:11)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="11.639"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.615"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.262">
    <failure type="java.lang.AssertionError" message="Error message mismatch! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message mismatch! expected [true] but found [false]
at stepDefinitions.NegativeAmountSteps.user_should_see_the_error_message_negative_amount(NegativeAmountSteps.java:81)
at ✽.User should see the error message "Invalid amount entered" for negative amount transfer(file:///C:/Users/dpraj/OneDrive/Desktop/Zero_Bank_demo/Zero_Capston_Project_demo/src/test/resources/features/NegativeAmount.feature:11)
... Removed 3 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.089"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.81"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.151"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.157"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.48"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.609"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.366"/>
</testsuite> <!-- ZeroBank Tests -->
